# Generated by Django 5.0.6 on 2024-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacionempleado',
            fields=[
                ('codigo_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(unique=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('tipo_de_sangre', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('fecha_de_nacimiento', models.DateField()),
                ('lugar_de_nacimiento', models.CharField(max_length=50)),
                ('estatura', models.CharField(choices=[('140 cm', '140 cm'), ('150 cm', '150 cm'), ('160 cm', '160 cm'), ('170 cm', '170 cm'), ('180 cm', '180 cm')], max_length=6)),
                ('peso', models.CharField(choices=[('40 kg', '40 kg'), ('50 kg', '50 kg'), ('60 kg', '60 kg'), ('70 kg', '70 kg'), ('80 kg', '80 kg'), ('90 kg', '90 kg')], max_length=6)),
                ('talla_camisa', models.CharField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('talla_sudadera', models.CharField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('talla_calzado', models.IntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')])),
                ('tiene_hijos', models.CharField(max_length=50)),
                ('estudios_realizados', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('union libre', 'Union Libre'), ('divorciado', 'Divorciado'), ('viudo/a', 'Viudo/a')], max_length=12)),
                ('tipo_de_vivienda', models.CharField(choices=[('propia', 'Propia'), ('arrendada', 'Arrendada'), ('familiar', 'Familiar')], max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('contacto', models.IntegerField()),
                ('contacto_de_emergencia', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=50)),
                ('restricciones_medicas', models.CharField(max_length=100)),
                ('arl', models.CharField(choices=[('axa colpatria', 'Axa Colpatria')], max_length=20)),
                ('riesgo_arl', models.FloatField()),
                ('eps', models.CharField(choices=[('sura eps', 'Sura EPS'), ('sanitas eps', 'Sanitas EPS'), ('nueva empresa promotora de salud', 'Nueva Empresa Promotora de Salud'), ('alianza medellin antioquia eps sas - savia salud', 'Alianza Medellin Antioquia EPS SAS - Savia Salud'), ('salud total eps', 'Salud Total EPS')], max_length=50)),
                ('administrador_fondo_de_pensiones', models.CharField(choices=[('proteccion', 'Protección'), ('colpensiones', 'Colpensiones'), ('porvenir', 'Porvenir'), ('colfondos', 'Colfondos'), ('skandia', 'Skandia')], max_length=20)),
                ('fondo_de_cesantias', models.CharField(choices=[('proteccion', 'Protección'), ('colfondos', 'Colfondos'), ('fondo nacional del ahorro', 'Fondo Nacional del Ahorro'), ('porvenir', 'Porvenir')], max_length=50)),
                ('tipo_de_contrato', models.CharField(choices=[('termino indefinido', 'Término Indefinido'), ('termino fijo', 'Término Fijo'), ('practicas', 'Prácticas')], max_length=20)),
                ('centro_de_costos', models.CharField(choices=[('I101', 'Gerencia'), ('I130', 'Sistemas'), ('I140', 'Auditoría'), ('I202', 'Gestión de Talento Humano'), ('I223', 'Seguridad'), ('I231', 'Servicios Generales'), ('I250', 'Estudiantes en Práctica'), ('I310', 'Coordinación Zona Franca'), ('I330', 'Financiera'), ('I360', 'Planeación'), ('I431', 'Compras'), ('I432', 'Comercio Exterior'), ('I502', 'Producto Terminado'), ('I520', 'Dirección Comercial'), ('I550', 'Dirección de Logística'), ('I560', 'Gerencia de Abastecimiento'), ('I1603', 'Ingeniería'), ('I647', 'Planta de Confección'), ('I648', 'Corte'), ('I651', 'Materias Primas'), ('I680', 'Calidad Producción'), ('I760', 'Laboratorio de Muestras'), ('I770', 'Desarrollo de Producto')], max_length=100)),
                ('area', models.CharField(choices=[('0', 'Prointimo'), ('2', 'Dirección Comercial'), ('3', 'Dirección Mercado y Diseño'), ('4', 'Técnica'), ('5', 'Dirección de Logística'), ('6', 'Materias Primas'), ('7', 'Laboratorio de Muestras'), ('8', 'Planta de Confección'), ('9', 'Corte'), ('10', 'Producto Terminado'), ('11', 'Calidad Producción'), ('12', 'Ingeniería'), ('13', 'Gestión de Talento Humano'), ('14', 'Sistemas'), ('15', 'Financiera'), ('17', 'Costos'), ('19', 'Comercio Exterior'), ('20', 'Coordinación Zona Franca'), ('23', 'Estudiantes en Práctica'), ('26', 'Preproducción Ropa Interior'), ('27', 'Auditoría'), ('28', 'Gerencia de Abastecimientos')], max_length=50)),
                ('cargo', models.CharField(choices=[('2', 'Director'), ('3', 'Gerente'), ('5', 'Coordinador Operativo'), ('6', 'Coordinador Administrativo'), ('7', 'Profesional'), ('8', 'Supervisor Operativo'), ('12', 'Auxiliar Operativo'), ('13', 'Auxiliar Administrativo'), ('14', 'Mecánico 1'), ('20', 'Operario 2'), ('22', 'Operario 3'), ('25', 'Aprendiz SENA'), ('26', 'Operario'), ('6036', 'Jefe'), ('60329', 'Auxiliar'), ('64717', 'Mecánico'), ('64731', 'Operario'), ('65131', 'Operario'), ('86331', 'Operario')], max_length=50)),
                ('nivel', models.CharField(choices=[('1', 'Alta Gerencia'), ('2', 'Gerencia Media 1'), ('3', 'Gerencia Media 2'), ('4', 'Nivel Supervisión'), ('5', 'Base Administrativa'), ('6', 'Base Operativa'), ('7', 'SENA')], max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
                ('fecha_de_retiro', models.DateField()),
                ('motivo_de_retiro', models.CharField(choices=[('renuncia voluntaria', 'Renuncia Voluntaria'), ('terminacion de contrato', 'Terminación de Contrato')], max_length=30)),
            ],
        ),
    ]
