# Generated by Django 5.0.6 on 2024-05-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionempleado',
            name='estudios_realizados',
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='codigo_empleado',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='contacto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='contacto_de_emergencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='riesgo_arl',
            field=models.CharField(choices=[('1.044', '1.044')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='tiene_hijos',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('informacion_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='empleados.informacionempleado')),
            ],
        ),
    ]
