# Generated by Django 5.0.6 on 2024-05-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_informacionempleado_estudios_realizados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionempleado',
            name='tiene_hijos',
        ),
    ]
