# Generated by Django 5.0.6 on 2024-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_informacionempleado_tiene_hijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempleado',
            name='fecha_de_retiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
