# Generated by Django 5.0.6 on 2024-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_informacionempleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionempleado',
            name='apellido',
            field=models.CharField(default='SIN APELLIDO', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estatura',
            field=models.CharField(choices=[('140 cm', '1,40 cm'), ('141 cm', '1,41 cm'), ('142 cm', '1,42 cm'), ('143 cm', '1,43 cm'), ('144 cm', '1,44 cm'), ('145 cm', '1,45 cm'), ('146 cm', '1,46 cm'), ('147 cm', '1,47 cm'), ('148 cm', '1,48 cm'), ('149 cm', '1,49 cm'), ('150 cm', '1,50 cm'), ('151 cm', '1,51 cm'), ('152 cm', '1,52 cm'), ('153 cm', '1,53 cm'), ('154 cm', '1,54 cm'), ('155 cm', '1,55 cm'), ('156 cm', '1,56 cm'), ('157 cm', '1,57 cm'), ('157 cm', '1,58 cm'), ('158 cm', '1,58 cm'), ('159 cm', '1,59 cm'), ('160 cm', '1,60 cm'), ('161 cm', '1,61 cm'), ('162 cm', '1,62 cm'), ('163 cm', '1,63 cm'), ('164 cm', '1,64 cm'), ('165 cm', '1,65 cm'), ('166 cm', '1,66 cm'), ('167 cm', '1,67 cm'), ('168 cm', '1,68 cm'), ('169 cm', '1,69 cm'), ('170 cm', '1,70 cm'), ('171 cm', '1,71 cm'), ('172 cm', '1,72 cm'), ('173 cm', '1,73 cm'), ('174 cm', '1,74 cm'), ('175 cm', '1,75 cm'), ('176 cm', '1,76 cm'), ('177 cm', '1,77 cm'), ('178 cm', '1,78 cm'), ('179 cm', '1,79 cm'), ('180 cm', '1,80 cm'), ('181 cm', '1,81 cm'), ('182 cm', '1,82 cm'), ('183 cm', '1,83 cm'), ('184 cm', '1,84 cm'), ('185 cm', '1,85 cm'), ('186 cm', '1,86 cm'), ('187 cm', '1,87 cm'), ('188 cm', '1,88 cm'), ('189 cm', '1,89 cm'), ('190 cm', '1,90 cm'), ('191 cm', '1,91 cm'), ('192 cm', '1,92 cm'), ('193 cm', '1,93 cm'), ('194 cm', '1,94 cm'), ('195 cm', '1,95 cm'), ('196 cm', '1,96 cm'), ('197 cm', '1,97 cm'), ('198 cm', '1,98 cm'), ('199 cm', '1,99 cm')], max_length=6),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
    ]
