# Generated by Django 5.0.6 on 2024-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_informacionempleado_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempleado',
            name='centro_de_costos',
            field=models.CharField(choices=[('I101', 'Direccion I101'), ('I130', 'Sistemas I130'), ('I140', 'Auditoría I140'), ('I202', 'Gestión de Talento Humano I202'), ('I223', 'Seguridad I223'), ('I231', 'Servicios Generales I231'), ('I250', 'Estudiantes en Práctica I250'), ('I310', 'Coordinación de Movimientos I310'), ('I330', 'Financiera I330'), ('I360', 'Planeación I360'), ('I431', 'Compras I431'), ('I432', 'Comercio Exterior I432'), ('I502', 'Producto Terminado I502'), ('I520', 'Dirección Comercial I520'), ('I550', 'Gerencia Operativa I550'), ('I560', 'Abastecimiento I560'), ('I1603', 'Ingeniería I1603'), ('I647', 'Planta de Confección I647'), ('I648', 'Corte I648'), ('I651', 'Materias Primas I651'), ('I663', 'Maquilas I663'), ('I680', 'Calidad Producción I680'), ('I760', 'Laboratorio de Muestras I760'), ('I770', 'Desarrollo de Producto ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union libre', 'Union Libre'), ('viudo/a', 'Viudo/a')], max_length=12),
        ),
    ]
