# Generated by Django 5.0.6 on 2024-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_alter_informacionempleado_centro_de_costos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionempleado',
            name='vehiculo',
            field=models.CharField(blank=True, choices=[('motocicleta', 'Motocicleta'), ('automovil', 'Automovil')], max_length=20, null=True),
        ),
    ]
