# Generated by Django 5.0.6 on 2024-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_informacionempleado_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=50),
            preserve_default=False,
        ),
    ]
