# Generated by Django 5.0.6 on 2024-06-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_hijo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempleado',
            name='centro_de_costos',
            field=models.CharField(choices=[('I101', 'I101'), ('I130', 'I130'), ('I140', 'I140'), ('I202', 'I202'), ('I223', 'I223'), ('I231', 'I231'), ('I250', 'I250'), ('I310', 'I310'), ('I330', 'I330'), ('I360', 'I360'), ('I431', 'I431'), ('I432', 'I432'), ('I502', 'I502'), ('I520', 'I520'), ('I550', 'I550'), ('I560', 'I560'), ('I1603', 'I1603'), ('I647', 'I647'), ('I648', 'I648'), ('I651', 'I651'), ('I663', 'I663'), ('I680', 'I680'), ('I760', 'I760'), ('I770', 'I770')], max_length=100),
        ),
        migrations.CreateModel(
            name='estudiosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(blank=True, choices=[('basica primaria', 'Basica Primaria'), ('basica secundaria', 'Basica Secundaria'), ('media tecnica', 'Media Tecnica'), ('tecnica', 'Tecnica'), ('tecnologo', 'Tecnologo'), ('profesional', 'Profesional'), ('postgrado', 'Postgrado'), ('maestria', 'Maestria')], max_length=50, null=True)),
                ('Area', models.CharField(blank=True, choices=[('artes y diseño', 'Artes y Diseño'), ('ciencias ambientales', 'Ciencias Ambientales'), ('ciencias de la salud', 'Ciencias de la Salud'), ('ciencias naturales y exactas', 'Ciencias Naturales y Exactas'), ('ciencias sociales', 'Ciencias Sociales'), ('comercio exterior', 'Comercio Exterior'), ('Comunicacion y periodismo', 'Comunicacion y Periodismo'), ('diseño de modas', 'Diseño de Modas'), ('educacion', 'Educacion'), ('humanidades', 'Humanidades'), ('ingenieria y tecnologia', 'Ingenieria y Tecnologia'), ('mercadotecnia de moda', 'Mercado Tecnica de Moda'), ('negocios y administracion', 'Negocios y Administracion'), ('nutricion y dietetica', 'Nutricion y Dietetica'), ('textil', 'textil'), ('veterinaria', 'veterinaria')], max_length=50, null=True)),
                ('Institucion', models.CharField(max_length=50)),
                ('informacionempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='empleados.informacionempleado')),
            ],
        ),
    ]
