# Generated by Django 5.0.6 on 2024-06-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0015_alter_estudiosrealizados_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hijo',
            name='edad',
        ),
        migrations.AddField(
            model_name='hijo',
            name='fecha_de_nacimiento',
            field=models.DateField(default='1999-01-23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiosrealizados',
            name='Area',
            field=models.CharField(blank=True, choices=[('Artes y diseño', 'Artes y Diseño'), ('Ciencias ambientales', 'Ciencias Ambientales'), ('Ciencias de la salud', 'Ciencias de la Salud'), ('Ciencias naturales y exactas', 'Ciencias Naturales y Exactas'), ('Ciencias sociales', 'Ciencias Sociales'), ('Comercio exterior', 'Comercio Exterior'), ('Comunicacion y periodismo', 'Comunicacion y Periodismo'), ('Bachiller academico', 'Bachiller Academico'), ('Diseño de modas', 'Diseño de Modas'), ('Educacion', 'Educacion'), ('Humanidades', 'Humanidades'), ('Ingenieria y tecnologia', 'Ingenieria y Tecnologia'), ('Mercadotecnia de moda', 'Mercado Tecnica de Moda'), ('Negocios y administracion', 'Negocios y Administracion'), ('Nutricion y dietetica', 'Nutricion y Dietetica'), ('Textil', 'textil'), ('Veterinaria', 'veterinaria')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudiosrealizados',
            name='Nivel',
            field=models.CharField(blank=True, choices=[('Basica primaria', 'Basica Primaria'), ('Basica secundaria', 'Basica Secundaria'), ('Media tecnica', 'Media Tecnica'), ('Tecnica', 'Tecnica'), ('Tecnologo', 'Tecnologo'), ('Profesional', 'Profesional'), ('Postgrado', 'Postgrado'), ('Maestria', 'Maestria')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='administrador_fondo_de_pensiones',
            field=models.CharField(choices=[('Proteccion', 'Protección'), ('Colpensiones', 'Colpensiones'), ('Porvenir', 'Porvenir'), ('Colfondos', 'Colfondos'), ('Skandia', 'Skandia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='arl',
            field=models.CharField(choices=[('Axa colpatria', 'Axa Colpatria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='eps',
            field=models.CharField(choices=[('Sura eps', 'Sura EPS'), ('Sanitas eps', 'Sanitas EPS'), ('Nueva empresa promotora de salud', 'Nueva Empresa Promotora de Salud'), ('Alianza medellin antioquia eps sas - savia salud', 'Alianza Medellin Antioquia EPS SAS - Savia Salud'), ('Salud total eps', 'Salud Total EPS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero/a'), ('Casado', 'Casado/a'), ('Union libre', 'Union Libre'), ('Viudo/a', 'Viudo/a')], max_length=12),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='fondo_de_cesantias',
            field=models.CharField(choices=[('Proteccion', 'Protección'), ('Colfondos', 'Colfondos'), ('Fondo nacional del ahorro', 'Fondo Nacional del Ahorro'), ('Porvenir', 'Porvenir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='motivo_de_retiro',
            field=models.CharField(blank=True, choices=[('Renuncia voluntaria', 'Renuncia Voluntaria'), ('Terminacion de contrato', 'Terminación de Contrato')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='tipo_de_contrato',
            field=models.CharField(choices=[('Termino indefinido', 'Término Indefinido'), ('Termino fijo', 'Término Fijo'), ('Practicas', 'Prácticas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='tipo_de_vivienda',
            field=models.CharField(choices=[('Propia', 'Propia'), ('Arrendada', 'Arrendada'), ('Familiar', 'Familiar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='informacionempleado',
            name='vehiculo',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Motocicleta', 'Motocicleta'), ('Automovil', 'Automovil')], max_length=20, null=True),
        ),
    ]
