# Generated by Django 5.0.6 on 2024-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0016_remove_hijo_edad_hijo_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempleado',
            name='centro_de_costos',
            field=models.CharField(choices=[('I101', 'Direccion I101'), ('I130', 'Sistemas I130'), ('I140', 'Auditoria I140'), ('I202', 'Gestion de Talento Humano I202'), ('I223', 'Seguridad I223'), ('I231', 'Servicios Generales y Aseo I231'), ('I250', 'Estudiantes en Practica I250'), ('I330', 'Financiera I330'), ('I432', 'Comercio Exterior I432'), ('I502', 'Producto Terminado I502'), ('I520', 'Comercial I520'), ('I760', 'Laboratorio de Muestras I760'), ('I770', 'Desarrollo de Producto I770'), ('I310', 'Coordinacion de Movimientos I310'), ('I360', 'Planeacion I360'), ('I431', 'Compras I431'), ('I550', 'Gerencia Operativa I550'), ('I560', 'Abastecimiento I560'), ('I603', ' Ingenieria I603'), ('I647', 'Planta de Confeccion I647'), ('I648', 'Corte I648'), ('I560', 'Abastecimiento I560'), ('I1603', 'Ingenieria I1603'), ('I647', 'Planta de Confeccion I647'), ('I648', 'Corte I648'), ('I651', 'Materias Primas I651'), ('I663', 'Maquilas I663'), ('I651', 'Materias Primas I651'), ('I663', 'Maquilas I663'), ('I680', 'Calidad Produccion I680')], max_length=100),
        ),
    ]
